### ISSUE TITLE
Problems with CIs for ssd_plot with censored data

### ISSUE THREAD

**Issue by beckyfisher** [poissonconsulting/ssdtools#44] opened 2024-04-11 06:23 UTC
library(ssdtools)
library(tidyverse)
#> Warning: package 'ggplot2' was built under R version 4.3.3
example_dat <- ssddata::ccme_boron |> 
  dplyr::mutate(left=Conc, right=Conc)

left_censored_example <- example_dat 
#left_censored_example$left[c(3,6,8)] <- NA

left_censored_dists <- ssd_fit_dists(left_censored_example, 
                                     dists = ssd_dists_bcanz(n = 2),
                                     left = "left", right = "right")
ssd_hc(left_censored_dists, average = FALSE)
#> # A tibble: 5 × 11
#>   dist    proportion   est    se   lcl   ucl     wt method   nboot pboot samples
#>   <chr>        <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl> <chr>    <int> <dbl> <I<lis>
#> 1 gamma         0.05  1.07    NA    NA    NA 0.367  paramet…     0    NA <dbl>  
#> 2 lgumbel       0.05  1.77    NA    NA    NA 0.0139 paramet…     0    NA <dbl>  
#> 3 llogis        0.05  1.56    NA    NA    NA 0.0676 paramet…     0    NA <dbl>  
#> 4 lnorm         0.05  1.68    NA    NA    NA 0.183  paramet…     0    NA <dbl>  
#> 5 weibull       0.05  1.09    NA    NA    NA 0.368  paramet…     0    NA <dbl>
ssd_hc(left_censored_dists)
#> # A tibble: 1 × 11
#>   dist    proportion   est    se   lcl   ucl    wt method    nboot pboot samples
#>   <chr>        <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <chr>     <int> <dbl> <I<lis>
#> 1 average       0.05  1.24    NA    NA    NA     1 parametr…     0    NA <dbl>
ssd_gof(left_censored_dists)
#> # A tibble: 5 × 9
#>   dist       ad     ks    cvm   aic  aicc   bic delta weight
#>   <chr>   <dbl>  <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>
#> 1 gamma   0.440 0.117  0.0554  238.  238.  240. 0.005  0.367
#> 2 lgumbel 0.829 0.158  0.134   244.  245.  247. 6.56   0.014
#> 3 llogis  0.487 0.0994 0.0595  241.  241.  244. 3.39   0.068
#> 4 lnorm   0.507 0.107  0.0703  239.  240.  242. 1.40   0.183
#> 5 weibull 0.434 0.117  0.0542  238.  238.  240. 0      0.368

set.seed(99)
left_censored_pred <- predict(left_censored_dists, ci = TRUE,  nboot = 100)

ssd_plot(left_censored_example, left_censored_pred,
         left = "left", right = "right",
         xlab = "Concentration (mg/L)"
)

Created on 2024-04-11 with [reprex v2.1.0](https://reprex.tidyverse.org/)

**Comment by joethorley** [comment] 2024-04-11 20:26
Thanks for reporting.

With resultant plot without censoring.

``` r
library(ssdtools)
library(tidyverse)
example_dat <- ssddata::ccme_boron |>
  dplyr::mutate(left=Conc, right=Conc)

left_censored_example <- example_dat
#left_censored_example$left[c(3,6,8)] <- NA

left_censored_dists <- ssd_fit_dists(left_censored_example,
                                     dists = ssd_dists_bcanz(n = 2),
                                     left = "left", right = "right")
ssd_hc(left_censored_dists, average = FALSE)
#> # A tibble: 5 × 11
#>   dist    proportion   est    se   lcl   ucl     wt method   nboot pboot samples
#>   <chr>        <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl> <chr>    <int> <dbl> <I<lis>
#> 1 gamma         0.05  1.07    NA    NA    NA 0.367  paramet…     0    NA <dbl>  
#> 2 lgumbel       0.05  1.77    NA    NA    NA 0.0139 paramet…     0    NA <dbl>  
#> 3 llogis        0.05  1.56    NA    NA    NA 0.0676 paramet…     0    NA <dbl>  
#> 4 lnorm         0.05  1.68    NA    NA    NA 0.183  paramet…     0    NA <dbl>  
#> 5 weibull       0.05  1.09    NA    NA    NA 0.368  paramet…     0    NA <dbl>

ssd_hc(left_censored_dists)
#> # A tibble: 1 × 11
#>   dist    proportion   est    se   lcl   ucl    wt method    nboot pboot samples
#>   <chr>        <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <chr>     <int> <dbl> <I<lis>
#> 1 average       0.05  1.24    NA    NA    NA     1 parametr…     0   NaN <dbl>

ssd_gof(left_censored_dists)
#> # A tibble: 5 × 9
#>   dist       ad     ks    cvm   aic  aicc   bic delta weight
#>   <chr>   <dbl>  <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>
#> 1 gamma   0.440 0.117  0.0554  238.  238.  240. 0.005  0.367
#> 2 lgumbel 0.829 0.158  0.134   244.  245.  247. 6.56   0.014
#> 3 llogis  0.487 0.0994 0.0595  241.  241.  244. 3.39   0.068
#> 4 lnorm   0.507 0.107  0.0703  239.  240.  242. 1.40   0.183
#> 5 weibull 0.434 0.117  0.0542  238.  238.  240. 0      0.368

set.seed(99)
left_censored_pred <- predict(left_censored_dists, ci = TRUE, nboot = 100)

ssd_plot(left_censored_example, left_censored_pred,
         left = "left", right = "right",
         xlab = "Concentration (mg/L)"
)
```

![](https://i.imgur.com/mM1N9Wu.png)

<sup>Created on 2024-04-11 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by joethorley** [comment] 2024-04-11 20:28
with censoring

``` r
library(ssdtools)
library(tidyverse)
example_dat <- ssddata::ccme_boron |>
  dplyr::mutate(left=Conc, right=Conc)

left_censored_example <- example_dat
left_censored_example$left[c(3,6,8)] <- NA

left_censored_dists <- ssd_fit_dists(left_censored_example,
                                     dists = ssd_dists_bcanz(n = 2),
                                     left = "left", right = "right")
ssd_hc(left_censored_dists, average = FALSE)
#> # A tibble: 5 × 11
#>   dist    proportion   est    se   lcl   ucl     wt method   nboot pboot samples
#>   <chr>        <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl> <chr>    <int> <dbl> <I<lis>
#> 1 gamma         0.05 0.674    NA    NA    NA 0.376  paramet…     0    NA <dbl>  
#> 2 lgumbel       0.05 1.51     NA    NA    NA 0.0221 paramet…     0    NA <dbl>  
#> 3 llogis        0.05 1.15     NA    NA    NA 0.0590 paramet…     0    NA <dbl>  
#> 4 lnorm         0.05 1.32     NA    NA    NA 0.176  paramet…     0    NA <dbl>  
#> 5 weibull       0.05 0.752    NA    NA    NA 0.367  paramet…     0    NA <dbl>

ssd_hc(left_censored_dists)
#> # A tibble: 1 × 11
#>   dist    proportion   est    se   lcl   ucl    wt method    nboot pboot samples
#>   <chr>        <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <chr>     <int> <dbl> <I<lis>
#> 1 average       0.05 0.859    NA    NA    NA     1 parametr…     0   NaN <dbl>

ssd_gof(left_censored_dists)
#> # A tibble: 5 × 9
#>   dist       ad    ks   cvm   aic  aicc   bic delta weight
#>   <chr>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>
#> 1 gamma      NA    NA    NA  222.    NA    NA 0      0.376
#> 2 lgumbel    NA    NA    NA  228.    NA    NA 5.67   0.022
#> 3 llogis     NA    NA    NA  226.    NA    NA 3.70   0.059
#> 4 lnorm      NA    NA    NA  224.    NA    NA 1.52   0.176
#> 5 weibull    NA    NA    NA  222.    NA    NA 0.046  0.367

set.seed(99)
left_censored_pred <- predict(left_censored_dists, ci = TRUE, nboot = 100)

ssd_plot(left_censored_example, left_censored_pred,
         left = "left", right = "right",
         xlab = "Concentration (mg/L)"
)
```

![](https://i.imgur.com/UEgBoiJ.png)

<sup>Created on 2024-04-11 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by joethorley** [comment] 2024-08-15 22:55
The problem is not with the plot but with the bootstrap intervals.

Here is a really simple reprex.

``` r
  library(ssdtools)
  data <- ssddata::ccme_boron
  data$right <- data$Conc
  data$Conc[c(3,6,8)] <- NA
  
  set.seed(100)
  fits <- ssd_fit_dists(data, dists = "lnorm", right = "right")
  ssd_hc(fits, ci = TRUE, nboot = 10)
#> # A tibble: 1 × 11
#>   dist    proportion   est     se     lcl   ucl    wt method nboot pboot samples
#>   <chr>        <dbl> <dbl>  <dbl>   <dbl> <dbl> <dbl> <chr>  <dbl> <dbl> <I<lis>
#> 1 average       0.05  1.32 0.0666 0.00183 0.188     1 param…    10     1 <dbl>
```

<sup>Created on 2024-08-15 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

where the ucl is less than the estimate!!

**Comment by beckyfisher** [comment] 2024-08-16 09:04
Ok, this seems like a problem, what is going on here? This is for a single distribution right? So nothing to do with the weighted bootstrap method?

**Comment by joethorley** [comment] 2024-08-16 15:09
The problem is how censored data is being handled during bootstrapping. I'll try and look into before the meeting.

This example indicates that if the data are not censored then the estimate lies within the lcl and ucl

``` r
  library(ssdtools)
  data <- ssddata::ccme_boron
  data$right <- data$Conc
 # data$Conc[c(3,6,8)] <- NA
  
  set.seed(100)
  fits <- ssd_fit_dists(data, dists = "lnorm", right = "right")
  ssd_hc(fits, ci = TRUE, nboot = 10)
#> # A tibble: 1 × 11
#>   dist    proportion   est    se   lcl   ucl    wt method    nboot pboot samples
#>   <chr>        <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <chr>     <dbl> <dbl> <I<lis>
#> 1 average       0.05  1.68 0.527  1.08  2.64     1 parametr…    10     1 <dbl>
```

<sup>Created on 2024-08-16 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by joethorley** [comment] 2024-08-16 21:22
The problem is that the censoring has only been applied to some of the data. When it is consistently applied across the data set then the bootstrap CIs are correct.

``` r
library(ssdtools)
library(tidyverse)
example_dat <- ssddata::ccme_boron |>
  dplyr::mutate(left=Conc, right=Conc)

left_censored_example <- example_dat
left_censored_example$left[left_censored_example$left < 4] <- NA

left_censored_dists <- ssd_fit_dists(left_censored_example,
                                     dists = ssd_dists_bcanz(n = 2),
                                     left = "left", right = "right")
ssd_hc(left_censored_dists, average = FALSE)
#> # A tibble: 4 × 11
#>   dist    proportion   est    se   lcl   ucl     wt method   nboot pboot samples
#>   <chr>        <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl> <chr>    <int> <dbl> <I<lis>
#> 1 gamma         0.05 0.415    NA    NA    NA 0.573  paramet…     0    NA <dbl>  
#> 2 llogis        0.05 1.01     NA    NA    NA 0.0162 paramet…     0    NA <dbl>  
#> 3 lnorm         0.05 1.01     NA    NA    NA 0.0173 paramet…     0    NA <dbl>  
#> 4 weibull       0.05 0.626    NA    NA    NA 0.394  paramet…     0    NA <dbl>

ssd_hc(left_censored_dists)
#> # A tibble: 1 × 11
#>   dist    proportion   est    se   lcl   ucl    wt method    nboot pboot samples
#>   <chr>        <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <chr>     <int> <dbl> <I<lis>
#> 1 average       0.05 0.505    NA    NA    NA     1 parametr…     0   NaN <dbl>

ssd_gof(left_censored_dists)
#> # A tibble: 5 × 9
#>   dist       ad    ks   cvm   aic  aicc   bic  delta weight
#>   <chr>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>  <dbl>
#> 1 gamma      NA    NA    NA  230.    NA    NA  0      0.573
#> 2 lgumbel    NA    NA    NA  245.    NA    NA 15.3    0    
#> 3 llogis     NA    NA    NA  237.    NA    NA  7.13   0.016
#> 4 lnorm      NA    NA    NA  237.    NA    NA  7.00   0.017
#> 5 weibull    NA    NA    NA  230.    NA    NA  0.751  0.393

set.seed(99)
left_censored_pred <- predict(left_censored_dists, ci = TRUE, nboot = 100)

ssd_plot(left_censored_example, left_censored_pred,
         left = "left", right = "right",
         xlab = "Concentration (mg/L)"
)
```

![](https://i.imgur.com/x0kDQSK.png)

<sup>Created on 2024-08-16 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by joethorley** [comment] 2024-08-17 01:20
Latest PR #74 

Now warns and doesn't calculate parametric CIs with partially censored data
``` r
library(ssdtools)
library(tidyverse)
example_dat <- ssddata::ccme_boron |>
  dplyr::mutate(left=Conc, right=Conc)

left_censored_example <- example_dat
left_censored_example$left[c(3,6,8)] <- NA

left_censored_dists <- ssd_fit_dists(left_censored_example,
                                     dists = ssd_dists_bcanz(n = 2),
                                     left = "left", right = "right")
left_censored_pred <- predict(left_censored_dists, ci = TRUE, nboot = 100)
#> Warning: Parametric CIs cannot be calculated for inconsistently censored data.

ssd_plot(left_censored_example, left_censored_pred,
         left = "left", right = "right",
         xlab = "Concentration (mg/L)"
)
```

![](https://i.imgur.com/IUKlhlW.png)

<sup>Created on 2024-08-16 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by joethorley** [comment] 2024-08-17 01:22
But works with non-parametric bootstrap

``` r
library(ssdtools)
library(tidyverse)
example_dat <- ssddata::ccme_boron |>
  dplyr::mutate(left=Conc, right=Conc)

left_censored_example <- example_dat
left_censored_example$left[c(3,6,8)] <- NA

left_censored_dists <- ssd_fit_dists(left_censored_example,
                                     dists = ssd_dists_bcanz(n = 2),
                                     left = "left", right = "right")
left_censored_pred <- predict(left_censored_dists, ci = TRUE, nboot = 100, parametric = FALSE)

ssd_plot(left_censored_example, left_censored_pred,
         left = "left", right = "right",
         xlab = "Concentration (mg/L)"
)
```

![](https://i.imgur.com/mrcXYLM.png)

<sup>Created on 2024-08-16 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by joethorley** [comment] 2024-08-17 01:30
I'm currently unsure why not calculating when completely censored...

``` r
library(ssdtools)
library(tidyverse)
example_dat <- ssddata::ccme_boron |>
  dplyr::mutate(left=Conc, right=Conc)

left_censored_example <- ssd_censor_data(example_dat, censoring = c(2.5, Inf))

left_censored_dists <- ssd_fit_dists(left_censored_example,
                                     dists = ssd_dists_bcanz(n = 2),
                                     left = "left", right = "right")
left_censored_pred <- predict(left_censored_dists, ci = TRUE, nboot = 100)
#> Warning: Parametric CIs cannot be calculated for inconsistently censored data.

ssd_plot(left_censored_example, left_censored_pred,
         left = "left", right = "right",
         xlab = "Concentration (mg/L)"
)
```

![](https://i.imgur.com/Bt4JSTJ.png)

<sup>Created on 2024-08-16 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by joethorley** [comment] 2024-08-19 15:48
Because I was being a dummy and not passing the correct columns to the fitting object.

Everything is working great now.

``` r
library(ssdtools)
library(tidyverse)
example_dat <- ssddata::ccme_boron |>
  dplyr::mutate(right=Conc)

left_censored_example <- ssd_censor_data(example_dat, censoring = c(2.5, Inf))

left_censored_dists <- ssd_fit_dists(left_censored_example,
                                     dists = ssd_dists_bcanz(n = 2), right = "right")

left_censored_pred <- predict(left_censored_dists, ci = TRUE, nboot = 100)

ssd_plot(left_censored_example, left_censored_pred,
         right = "right",
         xlab = "Concentration (mg/L)"
)
```

![](https://i.imgur.com/n8u3sYp.png)

<sup>Created on 2024-08-19 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by joethorley** [comment] 2024-08-19 15:53
This is resolved in https://github.com/poissonconsulting/ssdtools/tree/b-censorplot

**Closed as completed** 2024-08-19 22:02 UTC
Labels: Type: Bug, Difficulty: Advanced, Effort: Medium, Importance: High, Timeline: Now, zSkills: Software Development
